mod check;
mod compare;
mod detect;
mod erase;
mod fmap;
mod read;
mod regions;
mod sfdp;
mod watch;
mod write;

pub use check::cmd_check;
pub use compare::cmd_compare;
pub use detect::cmd_detect;
pub use erase::cmd_erase;
pub use fmap::cmd_fmap;
pub use read::cmd_read;
pub use regions::cmd_regions;
pub use sfdp::cmd_sfdp;
pub use watch::cmd_watch;
pub use write::cmd_write;
